-- disabled, I think this plugin is "too much", since I have my own tmux solutions
return {}
-- return {
--   'GustavEikaas/easy-dotnet.nvim',
--   cmd = 'Dotnet',
--   keys = {
--     { '<leader>rb', '<cmd>Dotnet build<CR>', desc = '[B]uild dotnet', silent = true },
--     { '<leader>rt', '<cmd>Dotnet test<CR>', desc = '[T]est dotnet', silent = true },
--   },
--   config = function()
--     local dotnet = require 'easy-dotnet'
--     dotnet.setup {
--       picker = 'telescope',
--       background_scanning = true,
--       notifications = {
--         --Set this to false if you have configured lualine to avoid double logging
--         handler = false,
--       },
--       debugger = {
--         --name if netcoredbg is in PATH or full path like 'C:\Users\gusta\AppData\Local\nvim-data\mason\bin\netcoredbg.cmd'
--         bin_path = 'netcoredbg',
--       },
--     }
--   end,
-- }
